FROM node:20
RUN apt-get update && apt-get install -y postgresql-client
ENV NODE_ENV=development
WORKDIR /app
COPY package.json .
RUN npm install
COPY . ./

RUN npm install -g nodemon

EXPOSE 8383
CMD ["npm", "run", "start"]